version: '3.8'

services:
  php-frontend:
    build:
      context: ./php-frontend
      args:
        BACKEND_URL: ${BACKEND_URL:-http://localhost:5001}
    ports:
      - "5002:80"
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://localhost:5001}
