version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_URL: ${BACKEND_URL:-http://52.205.19.193:5001}
    ports:
      - "5000:80"
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://52.205.19.193:5001}
