version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: testdb
    ports:
      - "5001:8000"
