version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "5555:3306"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: testdb
    ports:
      - "5001:8000"

  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_URL: ${BACKEND_URL:-http://localhost:5001}
    depends_on:
      - backend
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://localhost:5001}
    ports:
      - "5000:80"

volumes:
  dbdata:
