version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "5555:3306"

volumes:
  dbdata:
